[project]
name = "nv-sgl"
version = "0.15.0"
description = "Slang Graphics Library"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["setuptools", "wheel", "typing-extensions", "libcst"]
build-backend = "setuptools.build_meta"

[tool.pyright]
include = ["./src","./tools","./examples"]
extraPaths = ["./src/sgl/device/tests"]
ignore = ["./tools/host","./tools/download","./src/sgl/device/tests/test_torch_interop.py","./examples/torch_interop/torch_interop.py","./tools/msvc.py"]
pythonVersion = "3.9"
typeCheckingMode = "basic"
reportUnusedImport = "error"
reportMissingSuperCall  = "error"
reportInvalidStringEscapeSequence = "error"
reportMissingParameterType = "error"
reportMissingTypeArgument = "warning"
reportInvalidTypeForm = "warning"

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "typing-extensions>=4.13.2",
    "deepdiff>=8.4.2",
    "libcst>=1.7.0",
    "numpy>=2.0.2",
    "pyright>=1.1.400",
]
